// Code generated by "stringer -type=constraint -linecomment"; DO NOT EDIT.

package graphlator

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[and-0]
	_ = x[or-1]
	_ = x[not-2]
}

const _constraint_name = "ANDORNOT"

var _constraint_index = [...]uint8{0, 3, 5, 8}

func (i constraint) String() string {
	if i < 0 || i >= constraint(len(_constraint_index)-1) {
		return "constraint(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _constraint_name[_constraint_index[i]:_constraint_index[i+1]]
}
